language: python

python:
  - "3.6"


env:
  - DOCKER_COMPOSE_VERSION: 1.20.1

before_install:
  - sudo apt-get update
  - docker-compose --version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - docker ps
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker image pull bjmrq/airflow-reportpipeline
  - docker image pull postgres

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - docker-compose -f docker-compose-LocalExecutorTravis.yml up -d
  - sleep 30
  - docker exec -it airflow /bin/bash

script:
  - sleep 30
  - python -m unittest discover tests
