version: '2.2'
services:
    postgres:
        container_name: postgres
        image: postgres:9.6
        ports:
          - 5432
        environment:
          - POSTGRES_USER=airflow
          - POSTGRES_PASSWORD=airflow
          - POSTGRES_DB=airflow
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U airflow"]
          interval: 10s
          timeout: 5s
          retries: 5

    webserver:
        container_name: airflow
        image: bjmrq/airflow-reportpipeline
        restart: always
        depends_on:
          - postgres
        environment:
          - TRAVIS=Travis
          - LOAD_EX=n
          - EXECUTOR=Local
          - AIRFLOW__CORE__FERNET_KEY=uvFKCAi7qaHGm0eUjUiEWqTNa3LGI-UH_PFL3ta0iZ8=
        ports:
          - "8080:8080"
        command: webserver
        healthcheck:
          test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
          interval: 60s
          timeout: 60s
          retries: 3
