version: '2.2'
services:
    postgres:
        container_name: postgres
        image: postgres:9.6
        ports:
          - 5445:5432
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U airflow"]
          interval: 10s
          timeout: 5s
          retries: 5

    webserver:
        container_name: airflow
        image: bjmrq/airflow-reportpipeline
        restart: always
        depends_on:
          - postgres
        environment:
          - LOAD_EX=n
          - EXECUTOR=Local
        volumes:
          - ./dags:/usr/local/airflow/dags
          - ./plugins:/usr/local/airflow/plugins
          - ./tests:/usr/local/airflow/tests
          - ./data:/usr/local/airflow/data
        ports:
          - "8080:8080"
        command: webserver
        healthcheck:
          test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
          interval: 60s
          timeout: 60s
          retries: 3
